import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const require = createRequire(path.resolve(root, '../work/contract-review/package.json'));
const solc = require('solc');
const { ethers } = require('ethers');

function loadEnv(file) {
  if (!fs.existsSync(file)) return;
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
    if (match && !process.env[match[1]]) process.env[match[1]] = match[2].trim();
  }
}

loadEnv(path.join(root, '.env.local'));
loadEnv(path.join(root, '.env'));

const rpcUrl = process.env.RPC_URL || 'https://testrpc.xlayer.tech/terigon';
const expectedChainId = BigInt(process.env.CHAIN_ID || 1952);
if (!process.env.DEPLOYER_PRIVATE_KEY) throw new Error('DEPLOYER_PRIVATE_KEY is required in vadium/.env.local');

const contractsDir = path.join(root, 'contracts');
const sources = Object.fromEntries(
  fs.readdirSync(contractsDir).map((name) => [name, { content: fs.readFileSync(path.join(contractsDir, name), 'utf8') }]),
);
const output = JSON.parse(solc.compile(JSON.stringify({
  language: 'Solidity', sources,
  settings: { evmVersion: 'paris', optimizer: { enabled: true, runs: 200 }, outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } } },
})));
const errors = (output.errors ?? []).filter((issue) => issue.severity === 'error');
if (errors.length) throw new Error(errors.map((issue) => issue.formattedMessage).join('\n'));

const provider = new ethers.JsonRpcProvider(rpcUrl);
const network = await provider.getNetwork();
if (network.chainId !== expectedChainId) throw new Error(`RPC chain ${network.chainId} does not match configured chain ${expectedChainId}`);
const wallet = new ethers.Wallet(process.env.DEPLOYER_PRIVATE_KEY, provider);
const balance = await provider.getBalance(wallet.address);
if (balance === 0n) throw new Error(`Deployer ${wallet.address} has no OKB for gas`);
console.log(`Deploying Vadium demo from ${wallet.address} on chain ${network.chainId}...`);

async function deploy(file, name, args = []) {
  const artifact = output.contracts[file][name];
  const contract = await new ethers.ContractFactory(artifact.abi, artifact.evm.bytecode.object, wallet).deploy(...args);
  await contract.waitForDeployment();
  console.log(`${name}: ${await contract.getAddress()}`);
  return contract;
}

const stable = await deploy('MockERC20.sol', 'MockERC20', ['Demo USD', 'dUSD', 6]);
const stock = await deploy('MockERC20.sol', 'MockERC20', ['Apple xStock Demo', 'AAPLx', 18]);
const oracle = await deploy('MarketRiskOracle.sol', 'MarketRiskOracle', [wallet.address, 6 * 3600]);
await (await oracle.setPublisher(wallet.address, true)).wait();
const pool = await deploy('VadiumPool.sol', 'VadiumPool', [
  await stable.getAddress(), await stock.getAddress(), await oracle.getAddress(),
  6_500, 8_000, 7_500, 5_000, 3_000, 500, ethers.parseUnits('1000000', 6),
]);

await (await stable.mint(wallet.address, ethers.parseUnits('100000', 6))).wait();
await (await stock.mint(wallet.address, ethers.parseUnits('100', 18))).wait();
await (await stable.approve(await pool.getAddress(), ethers.parseUnits('50000', 6))).wait();
await (await pool.supply(ethers.parseUnits('50000', 6))).wait();
const block = await provider.getBlock('latest');
const inputBlob = ethers.toUtf8Bytes(JSON.stringify({ source: 'demo-seed', asset: 'AAPLx', price: 200 }));
await (await oracle.publish(await stock.getAddress(), {
  price: ethers.parseUnits('200', 18), freshnessBps: 10_000, liquidityBps: 10_000,
  asOf: block.timestamp, state: 0, inputsHash: ethers.keccak256(inputBlob),
})).wait();

const explorer = expectedChainId === 196n
  ? 'https://www.okx.com/web3/explorer/xlayer'
  : 'https://www.okx.com/web3/explorer/xlayer-test';
const browserConfig = `// Generated by scripts/deploy-demo.mjs. Contract addresses are public.\nwindow.VADIUM_CONFIG = Object.freeze(${JSON.stringify({
  chainId: Number(expectedChainId), rpcUrl, explorer,
  pool: await pool.getAddress(), oracle: await oracle.getAddress(),
  stable: await stable.getAddress(), collateral: await stock.getAddress(),
}, null, 2)});\n`;
fs.writeFileSync(path.join(root, 'deployment-config.js'), browserConfig);
fs.mkdirSync(path.join(root, 'deployments'), { recursive: true });
fs.writeFileSync(path.join(root, 'deployments', 'demo.local.json'), JSON.stringify({
  chainId: Number(expectedChainId), rpcUrl, explorer,
  pool: await pool.getAddress(), oracle: await oracle.getAddress(),
  stable: await stable.getAddress(), collateral: await stock.getAddress(),
}, null, 2));
console.log('Seeded 50,000 dUSD of pool liquidity and wrote deployment-config.js.');
